### ISSUE TITLE
Safari View Controller not presented

### ISSUE THREAD

**Issue by j-f1** [stleamist/BetterSafariView#8]
I have a `.safariView` attached to a `NavigationView` inside a sheet presented by another sheet. When I set the `item` for the safari view to a non-`nil` value, this error message is printed out and nothing happens on the screen. How can I fix this?

```
Attempt to present <SFSafariViewController: 0x10a020000>
on <_TtGC7SwiftUI19UIHostingControllerGVS_15ModifiedContentVS_7AnyViewVS_12RootModifier__: 0x104c0aad0> 
(from <_TtGC7SwiftUI19UIHostingControllerGVS_15ModifiedContentVS_7AnyViewVS_12RootModifier__: 0x104c0aad0>)
which is already presenting <_TtGC7SwiftUI29PresentationHostingControllerVS_7AnyView_: 0x108305f70>
```

**Comment by boherna** [comment]
This issue is already fixed in a pull request I just sent.

**Comment by Cay-Zhang** [comment]
The issue is still present with v2.2.2.

```
[Presentation] Attempt to present <SFSafariViewController: 0x15814e600> on
<_TtGC7SwiftUI19UIHostingControllerGVS_15ModifiedContentVS_7AnyViewVS_12RootModifier__: 0x157f11f30> (from
<_TtGC7SwiftUI19UIHostingControllerGVS_15ModifiedContentVS_7AnyViewVS_12RootModifier__: 0x157f11f30>) which is
already presenting <_TtGC7SwiftUI29PresentationHostingControllerVS_7AnyView_: 0x15930b270>.
```

I attached a `SafariView` to the root view and passed the `Binding<URL?>` down to other subviews. The problem occurred when I tried to present the `SafariView` by tapping a button on a sheet.

**Comment by boherna** [comment]
@Cay-Zhang v2.2.2 doesn't include my pull request.

**Comment by stleamist** [comment]
This issue is now fixed in v2.3.1 with the help of @boherna. Thank you for reporting this issue!

**Comment by twodayslate** [comment]
This is still present in the latest version

```
2021-09-09 23:03:02.949009-0400 BetterSafariViewDemo[72908:15428395] [Presentation] Attempt to present <SFSafariViewController: 0x13da59c00> on <_TtGC7SwiftUI29PresentationHostingControllerVS_7AnyView_: 0x140c0d020> (from <_TtGC7SwiftUI29PresentationHostingControllerVS_7AnyView_: 0x140c0d020>) which is already presenting <_TtGC7SwiftUI29PresentationHostingControllerVS_7AnyView_: 0x13ce9f0d0>.
```

Add the following to the demo RootView to duplicate

```swift
@State var showRootAgain = false
...
                Button("Open in sheet", action: {
                    self.showRootAgain.toggle()
                }).sheet(isPresented: $showRootAgain, content: {
                    RootView()
                })
```

**Comment by stleamist** [comment]
@twodayslate

The issue you have reported is now fixed in [v2.4.0](https://github.com/stleamist/BetterSafariView/releases/tag/v2.4.0). Check my comment on #20, and I really appreciate for your contribution!
